#include <string>
#include <unordered_map>

#include "cases.hh"

std::unordered_map<std::string, std::unordered_map<std::string, std::string>> lexer_cases = {
    /* {NAME, {INPUT, EXPECTED}} */

    {"Unterminated String Does Not Crash Process",                      {{"\"never closed", ""}}},
    {"Unterminated Multiline Comment Does Not Crash Process",           {{"##never closed", ""}}},
    {"All Hashes Multiline Comment Does Not Crash Process",             {{"####", ""}}},
    {"Fatal Error Mid-Stream Still Preserves Prior Tokens",             {{"var x = \"unterminated", "VAR(var) WHITESPACE( ) IDENTIFIER(x) WHITESPACE( ) ASSIGN(=) WHITESPACE( )"}}},
    {"Double Minus",                                                    {{"--5", "NEGATE(-) NEGATE(-) INT_LITERAL(5)"}}},
    {"Unary Negate On Identifier",                                      {{"-x", "NEGATE(-) IDENTIFIER(x)"}}},
    {"Binary Subtraction Between Identifiers",                          {{"a - b", "IDENTIFIER(a) WHITESPACE( ) SUB(-) WHITESPACE( ) IDENTIFIER(b)"}}},
    {"Negate After Open Paren",                                         {{"(-5)", "LPAREN(() NEGATE(-) INT_LITERAL(5) RPAREN())"}}},
    {"Subtraction After Close Paren",                                   {{"(a)-b", "LPAREN(() IDENTIFIER(a) RPAREN()) SUB(-) IDENTIFIER(b)"}}},
    {"Negate After Comma",                                              {{"f(a,-b)", "IDENTIFIER(f) LPAREN(() IDENTIFIER(a) COMMA(,) NEGATE(-) IDENTIFIER(b) RPAREN())"}}},
    {"Negate After Another Operator",                                   {{"a+-b", "IDENTIFIER(a) ADD(+) NEGATE(-) IDENTIFIER(b)"}}},
    {"Subtraction After Integer Literal",                               {{"5-3", "INT_LITERAL(5) SUB(-) INT_LITERAL(3)"}}},
    {"Negate At Start Of Input",                                        {{"-1", "NEGATE(-) INT_LITERAL(1)"}}},
    {"Negate After String Literal Is Subtraction",                      {{"\"a\"-1", "STRING_LITERAL(\"a\") SUB(-) INT_LITERAL(1)"}}},
    {"Single Unknown Character Produces No Token",                      {{"@", "ERROR(@)"}}},
    {"Multiple Unknown Characters Produce No Tokens",                   {{"@$^", "ERROR(@) ERROR($) ERROR(^)"}}},
    {"Unknown Character Silently Skipped Between Identifiers",          {{"foo@bar", "IDENTIFIER(foo) ERROR(@) IDENTIFIER(bar)"}}},
    {"Unknown Character Between Whitespace",                            {{"a @ b", "IDENTIFIER(a) WHITESPACE( ) ERROR(@) WHITESPACE( ) IDENTIFIER(b)"}}},
    {"Consecutive Unknown Characters",                                  {{"@@", "ERROR(@) ERROR(@)"}}},
    {"Single Integer",                                                  {{"42", "INT_LITERAL(42)"}}},
    {"Single-lined Comment",                                            {{"#hello\nworld", "COMMENT(#hello) WHITESPACE(\n) IDENTIFIER(world)"}}},
    {"String Escaping",                                                 {{"hello \"world\"", "IDENTIFIER(hello) WHITESPACE( ) STRING_LITERAL(\"world\")"}}},
    {"Var",                                                             {{"var", "VAR(var)"}}},
    {"Global",                                                          {{"global", "GLOBAL(global)"}}},
    {"Readonly",                                                        {{"readonly", "READONLY(readonly)"}}},
    {"If",                                                              {{"if", "IF(if)"}}},
    {"Func",                                                            {{"func", "FUNC(func)"}}},
    {"For",                                                             {{"for", "FOR(for)"}}},
    {"While",                                                           {{"while", "WHILE(while)"}}},
    {"Repeat",                                                          {{"repeat", "REPEAT(repeat)"}}},
    {"Until",                                                           {{"until", "UNTIL(until)"}}},
    {"Break",                                                           {{"break", "BREAK(break)"}}},
    {"Pass",                                                            {{"pass", "PASS(pass)"}}},
    {"In",                                                              {{"in", "IN(in)"}}},
    {"Include",                                                         {{"include", "INCLUDE(include)"}}},
    {"Using",                                                           {{"using", "USING(using)"}}},
    {"Export",                                                          {{"export", "EXPORT(export)"}}},
    {"Todo",                                                            {{"todo", "TODO(todo)"}}},
    {"And",                                                             {{"and", "AND(and)"}}},
    {"Or",                                                              {{"or", "OR(or)"}}},
    {"Else",                                                            {{"else", "ELSE(else)"}}},
    {"String",                                                          {{"String", "STRING(String)"}}},
    {"Char",                                                            {{"Char", "CHAR(Char)"}}},
    {"Number",                                                          {{"Number", "NUMBER(Number)"}}},
    {"Type Int Keyword",                                                {{"Int", "INTEGER(Int)"}}},
    {"Type Float Keyword",                                              {{"Float", "FLOAT(Float)"}}},
    {"Array Syntax",                                                    {{"String[]", "STRING(String) LBRACKET([) RBRACKET(])"}}},
    {"Assign",                                                          {{"=", "ASSIGN(=)"}}},
    {"Equals",                                                          {{"==", "EQUALS(==)"}}},
    {"Add",                                                             {{"+", "ADD(+)"}}},
    {"Add Assign",                                                      {{"+=", "ADD_ASSIGN(+=)"}}},
    {"Sub Assign",                                                      {{"-=", "SUB_ASSIGN(-=)"}}},
    {"Mul",                                                             {{"*", "MUL(*)"}}},
    {"Mul Assign",                                                      {{"*=", "MUL_ASSIGN(*=)"}}},
    {"Pow",                                                             {{"**", "POW(**)"}}},
    {"Pow Assign",                                                      {{"**=", "POW_ASSIGN(**=)"}}},
    {"Div",                                                             {{"/", "DIV(/)"}}},
    {"Div Assign",                                                      {{"/=", "DIV_ASSIGN(/=)"}}},
    {"Floor Div",                                                       {{"//", "FLOOR_DIV(//)"}}},
    {"Floor Div Assign",                                                {{"//=", "FLOOR_DIV_ASSIGN(//=)"}}},
    {"Remainder",                                                       {{"%", "REMAINDER(%)"}}},
    {"Remainder Assign",                                                {{"%=", "REMAINDER_ASSIGN(%=)"}}},
    {"Greater",                                                         {{">", "GREATER(>)"}}},
    {"Greater Equal",                                                   {{">=", "GREATER_EQUAL(>=)"}}},
    {"Less",                                                            {{"<", "LESS(<)"}}},
    {"Less Equal",                                                      {{"<=", "LESS_EQUAL(<=)"}}},
    {"Not",                                                             {{"!", "NOT(!)"}}},
    {"Not Equals",                                                      {{"!=", "NOT_EQUALS(!=)"}}},
    {"Not Null Assert",                                                 {{"!!", "NOT_NULL_ASSERT(!!)"}}},
    {"Question",                                                        {{"?", "QUESTION(?)"}}},
    {"Elvis",                                                           {{"?:", "ELVIS(?:)"}}},
    {"Basic Float",                                                     {{"3.14", "FLOAT_LITERAL(3.14)"}}},
    {"Trailing Dot With No Digit After",                                {{"5.", "INT_LITERAL(5) PERIOD(.)"}}},
    {"Integer Directly Followed By Letters",                            {{"42abc", "IDENTIFIER(42abc)"}}},
    {"Float Directly Followed By Letters",                              {{"1.5xyz", "IDENTIFIER(1.5xyz)"}}},
    {"Leading Zeros Preserved",                                         {{"007", "INT_LITERAL(007)"}}},
    {"Two Decimal Points In Sequence",                                  {{"1.2.3", "FLOAT_LITERAL(1.2) PERIOD(.) INT_LITERAL(3)"}}},
    {"Digits Then Underscore Then Letter",                              {{"10_x", "IDENTIFIER(10_x)"}}},
    {"Lone Period Alone",                                               {{".", "PERIOD(.)"}}},
    {"Empty String Literal",                                            {{"\"\"", "STRING_LITERAL(\"\")"}}},
    {"String With Newline Escape Sequence",                             {{"\"line\\nbreak\"", "STRING_LITERAL(\"line\\nbreak\")"}}},
    {"String With Invalid Escape Sequence",                             {{"\"bad\\qend\"", "STRING_LITERAL(\"bad\\qend\")"}}},
    {"String With Escaped Backslash",                                   {{"\"back\\\\slash\"", "STRING_LITERAL(\"back\\\\slash\")"}}},
    {"String With Tab Escape Sequence",                                 {{"\"col1\\tcol2\"", "STRING_LITERAL(\"col1\\tcol2\")"}}},
    {"String With Escaped Double Quotes Inside",                        {{"\"she said \\\"hi\\\"\"", "STRING_LITERAL(\"she said \\\"hi\\\"\")"}}},
    {"String Immediately Followed By Identifier",                       {{"\"abc\"def", "STRING_LITERAL(\"abc\") IDENTIFIER(def)"}}},
    {"Apostrophe Inside Double Quoted String",                          {{"\"it's fine\"", "STRING_LITERAL(\"it's fine\")"}}},
    {"Single Line Comment With No Trailing Newline",                    {{"#no newline here", "COMMENT(#no newline here)"}}},
    {"Single Hash With No Content",                                     {{"#", "COMMENT(#)"}}},
    {"Odd Delimiter Multiline Comment",                                 {{"###abc###", "MULTILINE_COMMENT(###abc###)"}}},
    {"Proper Multiline Comment",                                        {{"##hello##", "MULTILINE_COMMENT(##hello##)"}}},
    {"Multiline Comment With Mismatched Hash Count Inside",             {{"##a#b##", "MULTILINE_COMMENT(##a#b##)"}}},
    {"Comment Whitespace Then Comment",                                 {{"#first\n#second", "COMMENT(#first) WHITESPACE(\n) COMMENT(#second)"}}},
    {"Multiline Comment Directly Followed By Keyword",                  {{"##doc##var", "MULTILINE_COMMENT(##doc##) VAR(var)"}}},
    {"Single Line Comment With Hashes In Content",                      {{"#a#b#c", "COMMENT(#a#b#c)"}}},
    {"Mixed Whitespace Characters",                                     {{" \t\r\n", "WHITESPACE( \t\r\n)"}}},
    {"Only Whitespace No Other Tokens",                                 {{"   ", "WHITESPACE(   )"}}},
    {"Whitespace Between Two Identifiers",                              {{"foo   bar", "IDENTIFIER(foo) WHITESPACE(   ) IDENTIFIER(bar)"}}},
    {"Single Unknown Character Produces No Token",                      {{"@", ""}}},
    {"Multiple Unknown Characters Produce No Tokens",                   {{"@$^", ""}}},
    {"Unknown Character Silently Skipped Between Identifiers",          {{"foo@bar", "IDENTIFIER(foo) IDENTIFIER(bar)"}}},
    {"Variable Declaration Statement",                                  {{"var x = 10;", "VAR(var) WHITESPACE( ) IDENTIFIER(x) WHITESPACE( ) ASSIGN(=) WHITESPACE( ) INT_LITERAL(10) SEMICOLON(;)"}}},
    {"If Statement With Equality Comparison",                           {{"if a==b{}", "IF(if) WHITESPACE( ) IDENTIFIER(a) EQUALS(==) IDENTIFIER(b) LBRACE({) RBRACE(})"}}},
};